import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./filter.css";

import Header from "./components/header";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Chiton App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	auth,
}: {
	children: React.ReactNode;
	auth: React.ReactNode;
}) {

	return (
		<html lang="en">
			<body
				className={`${inter.className} relative flex flex-col min-h-[100vh] m-0 bg-[#FAF9F8]`}
			>
					{/* <Header /> */}
					{auth}
					{children}
					<Footer />
			</body>
		</html>
	);
}
