import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import UserContextProvider from './components/abc'
import Header from './components/header'
import Footer from './components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Chiton App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={`${inter.className} relative flex flex-col min-h-[100vh] m-0`}>
      <UserContextProvider>
        <Header/>
        {children}
        <Footer/>
      </UserContextProvider>
        </body>
        
      
    </html>
  )
}
